document.addEventListener('DOMContentLoaded',()=>{
 const c=new FileConverter(),drop=document.getElementById('dropZone'),input=document.getElementById('fileInput'),info=document.getElementById('fileInfo'),name=document.getElementById('fileName'),size=document.getElementById('fileSize'),preview=document.getElementById('filePreview'),remove=document.getElementById('removeFile'),from=document.getElementById('fromFormat'),to=document.getElementById('toFormat'),btn=document.getElementById('convertBtn'),result=document.getElementById('resultBox'),message=document.getElementById('resultMessage'),meta=document.getElementById('resultMeta'),download=document.getElementById('downloadConvertedBtn');
 let file=null,blob=null;
 const fmt=b=>`${(b/1024/1024).toFixed(2)} MB`;
 const targets={png:['jpg','webp','pdf'],jpg:['png','webp','pdf'],jpeg:['png','webp','pdf'],webp:['png','jpg','pdf'],gif:['png','jpg','webp','pdf'],bmp:['png','jpg','webp','pdf'],svg:['png','jpg','webp','pdf'],txt:['pdf','csv','json','xml','yaml','xlsx','docx','epub'],pdf:['png','jpg','txt'],csv:['xlsx','json','xml','yaml','txt','pdf'],json:['csv','xlsx','xml','yaml','txt','pdf'],xml:['json','csv','xlsx','yaml','txt','pdf'],yaml:['json','csv','xlsx','xml','txt','pdf'],yml:['json','csv','xlsx','xml','txt','pdf'],html:['pdf','txt'],htm:['pdf','txt'],xlsx:['csv','json','xml','yaml','txt','pdf'],docx:['txt','pdf'],epub:['txt','pdf'],fb2:['txt','pdf','epub']};
 function setTargets(ext){const list=targets[ext]||[];to.innerHTML=list.map(x=>`<option value="${x}">${x.toUpperCase()}</option>`).join('');if(!list.length)to.innerHTML='<option value="">Нет доступных направлений</option>';update();}
 function supported(){return !!file&&c.isConversionSupported(from.value,to.value)}
 function update(){btn.disabled=!supported();btn.title=supported()?'':'Для этого файла выберите поддерживаемый формат назначения.'}
 function escapeHtml(v){return String(v||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
 function setFile(f){if(!f)return;if(f.size>100*1024*1024){alert('Файл должен быть не больше 100 MB.');return;}file=f;blob=null;result.style.display='none';message.textContent='';meta.textContent='';name.textContent=f.name;size.textContent=fmt(f.size);info.style.display='block';preview.style.display='none';preview.innerHTML='';const ext=f.name.split('.').pop().toLowerCase();if(c.supportedInputs.includes(ext)){from.value=ext;setTargets(ext);}else{alert('Этот формат файла не поддерживается.');return;}if(ext==='heic') preview.innerHTML='<div style="padding:14px;color:#b45309">HEIC зависит от декодера браузера. Если превью не появилось, сохраните фото как JPG.</div>';update();}
 drop.addEventListener('click',()=>input.click());drop.addEventListener('dragover',e=>{e.preventDefault();drop.classList.add('dragover')});drop.addEventListener('dragleave',()=>drop.classList.remove('dragover'));drop.addEventListener('drop',e=>{e.preventDefault();drop.classList.remove('dragover');setFile(e.dataTransfer.files[0])});input.addEventListener('change',e=>setFile(e.target.files[0]));remove.addEventListener('click',()=>{file=null;blob=null;input.value='';info.style.display='none';preview.style.display='none';result.style.display='none';update()});from.addEventListener('change',()=>setTargets(from.value));to.addEventListener('change',update);
btn.addEventListener('click',async()=>{if(!file||btn.disabled)return;blob=null;result.style.display='none';btn.disabled=true;btn.textContent='Конвертация…';try{const r=await c.convert(file,from.value,to.value,{highQuality:document.getElementById('highQuality').checked,compress:document.getElementById('compress').checked});blob=r.blob;message.textContent=`Готово: ${from.value.toUpperCase()} → ${to.value.toUpperCase()}`;meta.textContent=`Размер ${fmt(r.size)} · ${r.duration} сек. · выполнено локально в браузере`;result.style.display='block';window.scrollTo({top:result.getBoundingClientRect().top+window.scrollY-80,behavior:'smooth'});}catch(e){console.error(e);alert(e.message)}finally{update();btn.textContent='Конвертировать'}});
 download.addEventListener('click',()=>{if(!blob)return;const save=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(blob);const ext=(blob.type==='application/zip'||to.value==='zip')?'zip':(to.value==='jpeg'?'jpg':to.value);a.download=`${file.name.replace(/\.[^.]+$/,'')}_converted.${ext}`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};if(window.adManager)window.adManager.requireVideoThen(save);else save()});
 update();
});
