(function(){
  const dict={
    ru:{nav:['Главная','Создать резюме','Конвертировать','Отзывы'],home:'Главная',create:'Создать резюме',convert:'Конвертировать',reviews:'Отзывы',
      next:'Далее',back:'Назад',reset:'Сбросить',download:'Скачать PDF',template:'Шаблон',dataPreview:'Данные и превью',chooseSystem:'Выберите визуальную систему',chooseDesc:'Все 7 вариантов имеют разную сетку, типографику и расположение блоков.',
      preview:'Предпросмотр A4',live:'LIVE',profile:'Профиль',skills:'Навыки',languages:'Языки',experience:'Опыт работы',education:'Образование',contact:'Контакты',about:'О себе',coreSkills:'Основные навыки',periodMissing:'Период не указан',educationTypes:{school:'Школа',college:'Среднее специальное',university:'Университет / вуз',other:'Образование'},
      languageLevels:['Не говорю','Начальный','Базовый','Средний','Рабочий уровень','Свободно владею','Родной язык'],defaultLanguage:'Русский',
      ui:{cv:'CURRICULUM VITAE',cv2026:'CURRICULUM VITAE · 2026',hello:'HELLO, I\'M',city:'Город проживания',desired:'Желаемая должность / профессиональная роль',company:'Компания',position:'Должность',university:'Университет / вуз',specialty:'Специальность',school:'Школа',classes:'Классов окончено',period:'Период',start:'Начало',end:'Окончание',untilNow:'По настоящее время',addExperience:'Добавить опыт',addEducation:'Добавить образование',addLanguage:'Добавить язык',personal:'Личные данные',photo:'Фото',uploadPhoto:'Загрузить фотографию',birth:'Дата рождения',gender:'Пол',male:'Мужской',female:'Женский',phone:'Телефон',email:'Email',marital:'Семейное положение',notSpecified:'Не указано',relocation:'Готовность к переезду',trips:'Командировки',salary:'Желаемая зарплата',currency:'Валюта',skillsProfile:'Навыки и профиль',startFilling:'Начните заполнять данные',dropFile:'Перетащите файл сюда или нажмите',chooseFile:'Выберите файл',converterTitle:'Конвертер файлов',converterHint:'Перетащите файл, который хотите конвертировать, выберите формат, в который хотите, и получите готовый результат в 2 клика.',history:'История конвертаций',historyPrivate:'История видна только вам на этом устройстве.',formats:'Формат',convertBtn:'Конвертировать',highQuality:'Высокое качество изображения',compress:'Сжатие результата'}},
    en:{nav:['Home','Create Resume','Convert Files','Reviews'],home:'Home',create:'Create Resume',convert:'Convert Files',reviews:'Reviews',next:'Next',back:'Back',reset:'Reset',download:'Download PDF',template:'Template',dataPreview:'Data & preview',chooseSystem:'Choose a visual system',chooseDesc:'All 7 options use different grids, typography and block layouts.',preview:'A4 Preview',live:'LIVE',profile:'Profile',skills:'Skills',languages:'Languages',experience:'Professional experience',education:'Education',contact:'Contact',about:'Profile',coreSkills:'Core skills',periodMissing:'Period not specified',educationTypes:{school:'School',college:'College',university:'University',other:'Education'},languageLevels:['Do not speak','Beginner','Basic','Intermediate','Working proficiency','Fluent','Native'],defaultLanguage:'English',ui:{cv:'CURRICULUM VITAE',cv2026:'CURRICULUM VITAE · 2026',hello:'HELLO, I\'M',city:'City',desired:'Desired position / professional role',company:'Company',position:'Position',university:'University',specialty:'Specialization',school:'School',classes:'Classes completed',period:'Period',start:'Start',end:'End',untilNow:'Present',addExperience:'Add experience',addEducation:'Add education',addLanguage:'Add language',personal:'Personal details',photo:'Photo',uploadPhoto:'Upload photo',birth:'Date of birth',gender:'Gender',male:'Male',female:'Female',phone:'Phone',email:'Email',marital:'Marital status',notSpecified:'Not specified',relocation:'Relocation',trips:'Business trips',salary:'Desired salary',currency:'Currency',skillsProfile:'Skills & profile',startFilling:'Start filling in your details',dropFile:'Drop a file here or click',chooseFile:'Choose a file',converterTitle:'File converter',converterHint:'Drop the file you want to convert, choose the output format, and get the result in 2 clicks.',history:'Conversion history',historyPrivate:'History is visible only to you on this device.',formats:'Format',convertBtn:'Convert',highQuality:'High image quality',compress:'Compress result'}},
    uz:{nav:['Bosh sahifa','Rezyume yaratish','Fayllarni konvertatsiya qilish','Sharhlar'],home:'Bosh sahifa',create:'Rezyume yaratish',convert:'Fayllarni konvertatsiya qilish',reviews:'Sharhlar',next:'Keyingi',back:'Orqaga',reset:'Tozalash',download:'PDF yuklab olish',template:'Shablon',dataPreview:'Maʼlumotlar va ko‘rish',chooseSystem:'Vizual uslubni tanlang',chooseDesc:'Barcha 7 variant turli tarmoq, tipografika va blok joylashuviga ega.',preview:'A4 ko‘rinishi',live:'LIVE',profile:'Profil',skills:'Ko‘nikmalar',languages:'Tillar',experience:'Ish tajribasi',education:'Taʼlim',contact:'Aloqa',about:'O‘zim haqimda',coreSkills:'Asosiy ko‘nikmalar',periodMissing:'Davr ko‘rsatilmagan',educationTypes:{school:'Maktab',college:'O‘rta maxsus',university:'Universitet',other:'Taʼlim'},languageLevels:['Gapirmayman','Boshlang‘ich','Bazaviy','O‘rta','Ish darajasi','Erkin','Ona tili'],defaultLanguage:'O‘zbek',ui:{cv:'CURRICULUM VITAE',cv2026:'CURRICULUM VITAE · 2026',hello:'SALOM, MEN',city:'Yashash shahri',desired:'Istalgan lavozim / professional rol',company:'Kompaniya',position:'Lavozim',university:'Universitet',specialty:'Mutaxassislik',school:'Maktab',classes:'Tugatilgan sinflar',period:'Davr',start:'Boshlanishi',end:'Tugashi',untilNow:'Hozirgacha',addExperience:'Ish tajribasi qo‘shish',addEducation:'Taʼlim qo‘shish',addLanguage:'Til qo‘shish',personal:'Shaxsiy maʼlumotlar',photo:'Foto',uploadPhoto:'Foto yuklash',birth:'Tug‘ilgan sana',gender:'Jins',male:'Erkak',female:'Ayol',phone:'Telefon',email:'Email',marital:'Oilaviy holat',notSpecified:'Ko‘rsatilmagan',relocation:'Ko‘chishga tayyorlik',trips:'Xizmat safarlari',salary:'Istalgan maosh',currency:'Valyuta',skillsProfile:'Ko‘nikmalar va profil',startFilling:'Maʼlumotlarni kiriting',dropFile:'Faylni shu yerga tashlang yoki bosing',chooseFile:'Fayl tanlang',converterTitle:'Fayl konvertori',converterHint:'Konvertatsiya qilmoqchi bo‘lgan faylni tashlang, kerakli formatni tanlang va natijani 2 bosishda oling.',history:'Konvertatsiya tarixi',historyPrivate:'Tarix faqat ushbu qurilmada sizga ko‘rinadi.',formats:'Format',convertBtn:'Konvertatsiya qilish',highQuality:'Yuqori tasvir sifati',compress:'Natijani siqish'}},
    kk:{nav:['Басты бет','Резюме жасау','Файлдарды түрлендіру','Пікірлер'],home:'Басты бет',create:'Резюме жасау',convert:'Файлдарды түрлендіру',reviews:'Пікірлер',next:'Келесі',back:'Артқа',reset:'Тазалау',download:'PDF жүктеу',template:'Үлгі',dataPreview:'Деректер және алдын ала көру',chooseSystem:'Көрнекі стильді таңдаңыз',chooseDesc:'7 нұсқаның әрқайсысында тор, типография және блоктардың орналасуы әртүрлі.',preview:'A4 алдын ала көру',live:'LIVE',profile:'Профиль',skills:'Дағдылар',languages:'Тілдер',experience:'Жұмыс тәжірибесі',education:'Білім',contact:'Байланыс',about:'Өзім туралы',coreSkills:'Негізгі дағдылар',periodMissing:'Кезең көрсетілмеген',educationTypes:{school:'Мектеп',college:'Арнаулы орта',university:'Университет',other:'Білім'},languageLevels:['Сөйлемеймін','Бастапқы','Негізгі','Орташа','Жұмыс деңгейі','Еркін сөйлеймін','Ана тілі'],defaultLanguage:'Қазақша',ui:{cv:'ТҮЙІНДЕМЕ',cv2026:'ТҮЙІНДЕМЕ · 2026',hello:'СӘЛЕМ, МЕН',city:'Тұрғылықты қала',desired:'Қалаған лауазым / кәсіби рөл',company:'Компания',position:'Лауазым',university:'Университет',specialty:'Мамандық',school:'Мектеп',classes:'Аяқталған сыныптар',period:'Кезең',start:'Басталуы',end:'Аяқталуы',untilNow:'Қазіргі уақытқа дейін',addExperience:'Тәжірибе қосу',addEducation:'Білім қосу',addLanguage:'Тіл қосу',personal:'Жеке мәліметтер',photo:'Фото',uploadPhoto:'Фото жүктеу',birth:'Туған күні',gender:'Жынысы',male:'Ер',female:'Әйел',phone:'Телефон',email:'Email',marital:'Отбасылық жағдай',notSpecified:'Көрсетілмеген',relocation:'Көшуге дайындық',trips:'Іссапарлар',salary:'Қалаған жалақы',currency:'Валюта',skillsProfile:'Дағдылар және профиль',startFilling:'Мәліметтерді енгізуді бастаңыз',dropFile:'Файлды осы жерге сүйреңіз немесе басыңыз',chooseFile:'Файл таңдаңыз',converterTitle:'Файл түрлендіргіші',converterHint:'Түрлендіргіңіз келетін файлды сүйреңіз, қажетті форматты таңдаңыз және нәтижені 2 қадамда алыңыз.',history:'Түрлендіру тарихы',historyPrivate:'Тарихты осы құрылғыда тек сіз көресіз.',formats:'Формат',convertBtn:'Түрлендіру',highQuality:'Жоғары сурет сапасы',compress:'Нәтижені сығу'}}
  };
  const exact={
    'Главная':'home','Создать резюме':'create','Конвертировать':'convert','Отзывы':'reviews','Далее →':'next','← Назад':'back','↺ Сбросить':'reset','↓  Скачать PDF':'download','↓ Скачать PDF':'download','Шаблон':'template','Данные и превью':'dataPreview','Выберите визуальную систему':'chooseSystem','Все 7 вариантов имеют разную сетку, типографику и расположение блоков.':'chooseDesc','Предпросмотр A4':'preview','Начните заполнять данные':'startFilling','Опыт работы':'experience','Образование':'education','Навыки':'skills','Языки':'languages','О себе':'about','Профиль':'profile','Контакты':'contact','Основные навыки':'coreSkills','Период не указан':'periodMissing'};
  function locale(){return 'ru'}
  function d(){return dict[locale()]||dict.ru}
  function t(key){const x=d(); return key.split('.').reduce((a,k)=>a?.[k],x) ?? key}
  function setLocale(){localStorage.setItem('nextresume_locale','ru');apply();document.dispatchEvent(new CustomEvent('nextresume:locale',{detail:'ru'}));}
  function apply(){
    document.documentElement.lang=locale()==='kk'?'kk':locale();
    const s=document.getElementById('languageSwitcher'); if(s) s.remove();
    const valueMap={...exact}; Object.entries(dict).forEach(([lang,obj])=>{const scan=(o,path=[])=>{Object.entries(o||{}).forEach(([k,v])=>{if(typeof v==='string') valueMap[v]=path.concat(k).join('.'); else if(Array.isArray(v)) v.forEach(x=>{if(typeof x==='string') valueMap[x]=path.concat(k).join('.__array');}); else if(v&&typeof v==='object') scan(v,path.concat(k));});};scan(obj);}); const walk=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);const nodes=[];while(walk.nextNode())nodes.push(walk.currentNode);nodes.forEach(n=>{const v=n.nodeValue.trim();const key=valueMap[v];if(key&&!key.endsWith('.__array')){const lead=n.nodeValue.match(/^\s*/)?.[0]||'';const trail=n.nodeValue.match(/\s*$/)?.[0]||'';n.nodeValue=lead+t(key)+trail;}});
    const ids={city:'ui.city',desiredPosition:'ui.desired',salary:'ui.salary',phone:'ui.phone',email:'ui.email',about:'about',skills:'skills'};Object.entries(ids).forEach(([id,k])=>{const el=document.getElementById(id);if(el&&el.previousElementSibling?.tagName==='LABEL')el.previousElementSibling.textContent=t(k);});
  }
  window.NextI18n={dict,t,locale,setLocale,apply};
  document.addEventListener('DOMContentLoaded',apply);
})();
