/* NextResume: deterministic canvas PDF renderer. Avoids foreignObject/html-to-canvas black-screen failures. */
window.NextResumeResumePDF = (() => {
  const W=1240,H=1754, PAD=78;
  const C={ink:'#172033',muted:'#667085',line:'#d8dee8',purple:'#7c3aed',blue:'#1769aa',red:'#ef4444',dark:'#111827',lav:'#f4f1ff'};
  const esc = v => String(v ?? '');
  function loadImg(src){return new Promise((resolve,reject)=>{if(!src)return resolve(null);const i=new Image();i.onload=()=>resolve(i);i.onerror=()=>reject(new Error('Не удалось загрузить фото для PDF.'));i.src=src;});}
  function wrap(ctx,text,maxWidth){
    const words=esc(text).replace(/\s+/g,' ').trim().split(' ').filter(Boolean); if(!words.length)return [];
    const lines=[]; let line=''; for(const word of words){const test=line?line+' '+word:word;if(ctx.measureText(test).width<=maxWidth)line=test;else{if(line)lines.push(line);line=word;}}
    if(line)lines.push(line); return lines;
  }
  function drawText(ctx,text,x,y,maxWidth,lh=26,font='16px Arial',color=C.ink,maxLines=999){ctx.font=font;ctx.fillStyle=color;let lines=wrap(ctx,text,maxWidth);if(lines.length>maxLines)lines=lines.slice(0,maxLines);for(const l of lines){ctx.fillText(l,x,y);y+=lh;}return y;}
  function drawPhoto(ctx,img,x,y,w,h){if(!img)return;ctx.save();ctx.beginPath();ctx.rect(x,y,w,h);ctx.clip();const s=Math.max(w/img.width,h/img.height),iw=img.width*s,ih=img.height*s;ctx.drawImage(img,x+(w-iw)/2,y+(h-ih)/2,iw,ih);ctx.restore();}
  function line(ctx,x1,y1,x2,y2,color=C.line,width=1){ctx.strokeStyle=color;ctx.lineWidth=width;ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.stroke();}
  function sectionTitle(ctx,title,x,y,w,color=C.ink){ctx.font='700 15px Arial';ctx.fillStyle=color;ctx.fillText(title.toUpperCase(),x,y);line(ctx,x,y+10,x+w,y+10,color,1);return y+34;}
  function normalize(d){return {name:[d.firstName,d.middleName,d.lastName].filter(Boolean).join(' ')||'Ваше имя',title:d.desiredPosition||'Желаемая должность',email:d.email||'',phone:d.phone||'',city:d.city||'',about:d.about||'',skills:String(d.hardSkills||'').split(',').map(x=>x.trim()).filter(Boolean),languages:String(d.languages||'').split(',').map(x=>x.trim()).filter(Boolean),experience:Array.isArray(d.experience)?d.experience:[],education:Array.isArray(d.education)?d.education:[],salary:d.salary||'',currency:d.currency||'',photo:d.photo||null,template:Number(d.template)||1};}
  function period(e){const f=v=>v?new Date(v+'T00:00:00').toLocaleDateString('ru-RU',{month:'short',year:'numeric'}).replace('.',''):'';return [f(e.startDate),e.current?'по настоящее время':f(e.endDate)].filter(Boolean).join(' — ');}
  function contact(d){return [d.email,d.phone,d.city].filter(Boolean).join('  •  ');}
  function createPage(bg='#fff'){const c=document.createElement('canvas');c.width=W;c.height=H;const x=c.getContext('2d');x.fillStyle=bg;x.fillRect(0,0,W,H);return {c,x};}
  function addPage(pages,bg='#fff'){const p=createPage(bg);pages.push(p);return p;}
  function drawExperience(ctx,d,x,y,w,style){for(const e of d.experience){ctx.font='700 17px Arial';ctx.fillStyle=style.ink;ctx.fillText(e.position||'Должность',x,y);ctx.font='14px Arial';ctx.fillStyle=style.accent||C.muted;ctx.textAlign='right';ctx.fillText(period(e),x+w,y);ctx.textAlign='left';y+=25;ctx.font='600 14px Arial';ctx.fillStyle=style.company||style.ink;ctx.fillText(e.company||'Компания',x,y);y+=25;if(e.description)y=drawText(ctx,e.description,x,y,w,22,'13px Arial',style.text||C.muted)+14;line(ctx,x,y-6,x+w,y-6,style.line||C.line);y+=12;}return y;}
  function drawEducation(ctx,d,x,y,w,style){for(const e of d.education){ctx.font='700 15px Arial';ctx.fillStyle=style.ink;ctx.fillText(e.institution||'Учебное заведение',x,y);y+=22;if(e.degree){ctx.font='13px Arial';ctx.fillStyle=style.text||C.muted;ctx.fillText(e.degree,x,y);y+=21;}if(e.year){ctx.font='12px Arial';ctx.fillStyle=style.accent||C.muted;ctx.fillText(e.year,x,y);y+=21;}y+=10;}return y;}
  function drawSkills(ctx,d,x,y,w,style){ctx.font='12px Arial';let xx=x,yy=y;for(const s of d.skills){const tw=ctx.measureText(s).width+24;if(xx+tw>x+w){xx=x;yy+=30;}ctx.fillStyle=style.fill||'#eef2f6';ctx.fillRect(xx,yy-18,tw,24);ctx.fillStyle=style.text||C.ink;ctx.fillText(s,xx+12,yy-2);xx+=tw+7;}return yy+20;}
  function drawCommonMain(ctx,d,x,y,w,style){if(d.about){y=sectionTitle(ctx,'О себе',x,y,w,style.accent||style.ink);y=drawText(ctx,d.about,x,y,w,22,'13px Arial',style.text||C.muted)+18;}if(d.experience.length){y=sectionTitle(ctx,'Опыт работы',x,y,w,style.accent||style.ink);y=drawExperience(ctx,d,x,y,w,style)+8;}if(d.education.length){y=sectionTitle(ctx,'Образование',x,y,w,style.accent||style.ink);y=drawEducation(ctx,d,x,y,w,style)+8;}return y;}
  function renderTemplate(d,pages,img){
    let p=pages[0],ctx=p.x,y=0;
    const addOverflow=(bg='#fff')=>{p=addPage(pages,bg);ctx=p.x;y=PAD;return p;};
    const ensure=need=>{if(y+need>H-PAD){addOverflow();return true}return false;};
    const style={ink:C.ink,text:C.muted,line:C.line,accent:C.purple};
    switch(d.template){
      case 2:{ctx.fillStyle='#172033';ctx.fillRect(0,0,300,H);drawPhoto(ctx,img,80,70,140,140);ctx.fillStyle='#f8fafc';ctx.font='700 26px Arial';ctx.fillText(d.name.split(' ')[0]||'Имя',45,255);ctx.font='14px Arial';ctx.fillStyle='#c7d2fe';ctx.fillText(d.title,45,282);ctx.font='12px Arial';ctx.fillStyle='#d7deea';let sy=340;for(const t of [d.phone,d.email,d.city].filter(Boolean)){sy=drawText(ctx,t,45,sy,210,20,'12px Arial','#d7deea')+10;}if(d.skills.length){sy=sectionTitle(ctx,'Навыки',45,sy,210,'#a5b4fc');sy=drawSkills(ctx,d,45,sy,210,{fill:'#27344d',text:'#e5e7eb'})}if(d.languages.length){sy=sectionTitle(ctx,'Языки',45,sy,210,'#a5b4fc');sy=drawText(ctx,d.languages.join(' • '),45,sy,210,21,'12px Arial','#d7deea')+10;}ctx.fillStyle=C.ink;ctx.font='700 42px Arial';ctx.fillText(d.name,345,95);ctx.font='18px Arial';ctx.fillStyle=C.muted;ctx.fillText(d.title,345,128);line(ctx,345,150,1160,150,C.line,2);y=195;const mainStyle={ink:C.ink,text:C.muted,line:C.line,accent:'#7c6cff',company:C.ink};if(d.about){y=sectionTitle(ctx,'О себе',345,y,815,C.ink);y=drawText(ctx,d.about,345,y,815,22,'13px Arial',C.muted)+18;}if(d.experience.length){y=sectionTitle(ctx,'Опыт',345,y,815,C.ink);y=drawExperience(ctx,d,345,y,815,mainStyle)+8;}if(d.education.length){y=sectionTitle(ctx,'Образование',345,y,815,C.ink);drawEducation(ctx,d,345,y,815,mainStyle);}break;}
      case 3:{ctx.fillStyle=C.red;ctx.font='800 16px Arial';ctx.fillText('03',PAD,90);drawPhoto(ctx,img,1050,52,100,100);ctx.fillStyle=C.ink;ctx.font='800 52px Arial';ctx.fillText(d.name,130,92);ctx.font='18px Arial';ctx.fillStyle=C.muted;ctx.fillText(d.title,130,123);ctx.font='12px Arial';ctx.fillText(contact(d),130,155);line(ctx,PAD,185,W-PAD,185,C.ink,2);const mainW=760;let yy=235;yy=drawCommonMain(ctx,d,PAD,yy,mainW,{ink:C.ink,text:C.muted,line:C.line,accent:C.red,company:C.ink});let sx=890,sy=235;if(d.skills.length){sy=sectionTitle(ctx,'Навыки',sx,sy,270,C.red);sy=drawSkills(ctx,d,sx,sy,270,{fill:'#111827',text:'#fff'})}if(d.languages.length){sy=sectionTitle(ctx,'Языки',sx,sy,270,C.red);drawText(ctx,d.languages.join(' • '),sx,sy,270,22,'13px Arial',C.muted);}break;}
      case 4:{ctx.fillStyle=C.lav;ctx.fillRect(0,0,W,310);ctx.fillStyle=C.purple;ctx.fillRect(0,0,12,H);drawPhoto(ctx,img,70,60,120,120);ctx.fillStyle='#24133f';ctx.font='800 44px Arial';ctx.fillText(d.name,225,105);ctx.font='18px Arial';ctx.fillStyle=C.purple;ctx.fillText(d.title,225,138);ctx.font='12px Arial';ctx.fillStyle=C.muted;ctx.fillText(contact(d),225,166);let yy=360;const left=290,right=820;let sy=yy;if(d.skills.length){sy=sectionTitle(ctx,'Навыки',PAD,sy,left,C.purple);sy=drawSkills(ctx,d,PAD,sy,left,{fill:'#f1eafd',text:'#5b21b6'})}if(d.languages.length){sy=sectionTitle(ctx,'Языки',PAD,sy,left,C.purple);sy=drawText(ctx,d.languages.join(' • '),PAD,sy,left,22,'13px Arial',C.muted)+15;}drawCommonMain(ctx,d,400,yy,right,{ink:'#24133f',text:C.muted,line:'#e5def2',accent:C.purple,company:C.purple});break;}
      case 5:{ctx.fillStyle='#111827';ctx.fillRect(0,0,W,270);drawPhoto(ctx,img,1050,50,110,110);ctx.fillStyle='#fff';ctx.font='800 40px Arial';ctx.fillText(d.name,70,100);ctx.font='17px Arial';ctx.fillStyle='#c7d2fe';ctx.fillText(d.title,70,132);ctx.font='12px Arial';ctx.fillStyle='#d1d5db';ctx.fillText(contact(d),70,164);let yy=325;yy=drawCommonMain(ctx,d,70,yy,800,{ink:C.ink,text:C.muted,line:C.line,accent:C.ink,company:C.ink});let sy=325;if(d.skills.length){sy=sectionTitle(ctx,'Ключевые навыки',920,sy,240,C.ink);sy=drawSkills(ctx,d,920,sy,240,{fill:'#fff',text:C.ink})}if(d.languages.length){sy=sectionTitle(ctx,'Языки',920,sy,240,C.ink);sy=drawText(ctx,d.languages.join(' • '),920,sy,240,21,'12px Arial',C.muted)+12;}break;}
      case 6:{ctx.fillStyle='#e9f2f8';ctx.fillRect(0,0,W,250);drawPhoto(ctx,img,70,50,100,115);ctx.fillStyle='#163a5f';ctx.font='800 36px Arial';ctx.fillText(d.name,200,95);ctx.font='16px Arial';ctx.fillStyle='#60758b';ctx.fillText(d.title,200,125);ctx.font='12px Arial';ctx.fillText(contact(d),200,155);let yy=300;yy=drawCommonMain(ctx,d,70,yy,780,{ink:C.ink,text:C.muted,line:C.line,accent:C.blue,company:C.ink});let sy=300;if(d.skills.length){sy=sectionTitle(ctx,'Компетенции',900,sy,240,C.blue);sy=drawSkills(ctx,d,900,sy,240,{fill:'#e9f2f8',text:'#17537e'})}if(d.languages.length){sy=sectionTitle(ctx,'Языки',900,sy,240,C.blue);drawText(ctx,d.languages.join(' • '),900,sy,240,21,'12px Arial',C.muted)}break;}
      case 7:{ctx.fillStyle=C.ink;ctx.fillRect(0,0,W,6);if(img)drawPhoto(ctx,img,577,55,86,86);ctx.fillStyle=C.ink;ctx.textAlign='center';ctx.font='800 38px Georgia';ctx.fillText(d.name,W/2,180);ctx.font='italic 17px Georgia';ctx.fillStyle=C.muted;ctx.fillText(d.title,W/2,208);ctx.font='12px Georgia';ctx.fillText(contact(d),W/2,234);ctx.textAlign='left';line(ctx,PAD,265,W-PAD,265,C.ink,2);let yy=310;yy=drawCommonMain(ctx,d,PAD,yy,760,{ink:C.ink,text:C.muted,line:C.line,accent:C.ink,company:C.ink});let sy=310;if(d.skills.length){sy=sectionTitle(ctx,'Ключевые навыки',900,sy,240,C.ink);sy=drawSkills(ctx,d,900,sy,240,{fill:'#f3f4f6',text:C.ink})}if(d.languages.length){sy=sectionTitle(ctx,'Языки',900,sy,240,C.ink);drawText(ctx,d.languages.join(' • '),900,sy,240,21,'12px Georgia',C.muted)}break;}
      default:{drawPhoto(ctx,img,70,60,110,110);ctx.fillStyle=C.ink;ctx.font='800 42px Georgia';ctx.fillText(d.name,205,100);ctx.font='17px Arial';ctx.fillStyle=C.muted;ctx.fillText(d.title,205,130);ctx.font='12px Arial';ctx.fillText(contact(d),205,160);line(ctx,70,195,1170,195,C.ink,6);let yy=245;const left=270;yy=sectionTitle(ctx,'Профиль',70,yy,left,C.ink);if(d.about)yy=drawText(ctx,d.about,70,yy,left,22,'13px Georgia',C.muted)+15;if(d.skills.length){yy=sectionTitle(ctx,'Навыки',70,yy,left,C.ink);yy=drawSkills(ctx,d,70,yy,left,{fill:'#eef2f6',text:C.ink})}let sy=245;sy=drawCommonMain(ctx,d,400,sy,770,{ink:C.ink,text:C.muted,line:C.line,accent:C.ink,company:C.ink});}
    }
    return pages;
  }
  async function generate(data){const d=normalize(data),pages=[createPage('#fff')],img=await loadImg(d.photo);renderTemplate(d,pages,img);const usable=pages.map(p=>NextResumePDF.canvasPage(p.c));return NextResumePDF.buildPdf(usable);}
  return {generate};
})();
